<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModulesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $modules = [
            [
                'slug' => 'ui-ux',
                'name' => 'UI / UX',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 3000,
                'earlybird_fee' => 2500,
                'image' => 'images/ux-design.png',
                'description' => 'Learn to design user-friendly interfaces for apps and websites. Master the principles of user experience design, create wireframes, prototypes, and beautiful interfaces that users love.',
            ],
            [
                'slug' => 'bridge-designing',
                'name' => 'Bridge Designing',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 3,
                'fee' => 1500,
                'earlybird_fee' => 1200,
                'image' => 'images/bridge.png',
                'description' => 'Construct virtual or model bridges with engineering principles. Learn structural analysis, load calculations, and create impressive bridge designs using modern engineering software.',
            ],
            [
                'slug' => 'speed-cad',
                'name' => 'Speed CAD',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1200,
                'earlybird_fee' => 1000,
                'image' => 'images/software.png',
                'description' => 'Master quick and precise CAD designs. Learn advanced CAD techniques, shortcuts, and create professional technical drawings in record time.',
            ],
            [
                'slug' => 'technopreneurship',
                'name' => 'Technopreneurship',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1800,
                'earlybird_fee' => 1500,
                'image' => 'images/business-computer.png',
                'description' => 'Present your major project to peers and mentors. Learn to pitch your ideas, develop business plans, and turn your technical skills into entrepreneurial ventures.',
            ],
            [
                'slug' => 'speed-coding',
                'name' => 'Speed Coding',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1400,
                'earlybird_fee' => 1200,
                'image' => 'images/laptop-computer.png',
                'description' => 'Solve coding challenges quickly and efficiently. Master algorithms, data structures, and competitive programming techniques to become a faster, more efficient coder.',
            ],
            [
                'slug' => 'database-designing',
                'name' => 'Database Designing',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1600,
                'earlybird_fee' => 1300,
                'image' => 'images/database.png',
                'description' => 'Structure data for apps and websites effectively. Learn database design principles, normalization, indexing, and create efficient database schemas for real-world applications.',
            ],
            [
                'slug' => '3d-modelling',
                'name' => '3D Modelling',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 2000,
                'earlybird_fee' => 1700,
                'image' => 'images/model.png',
                'description' => 'Create 3D designs for games, models, and prototypes. Master 3D modeling software, learn texturing, lighting, and create stunning 3D assets for various applications.',
            ],
            [
                'slug' => 'ethical-hacking',
                'name' => 'Ethical Hacking',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 2200,
                'earlybird_fee' => 1900,
                'image' => 'images/cyber-attack.png',
                'description' => 'Explore cybersecurity and protect systems ethically. Learn penetration testing, vulnerability assessment, and ethical hacking techniques to secure digital systems.',
            ],
            [
                'slug' => 'debugging',
                'name' => 'Debugging',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1300,
                'earlybird_fee' => 1100,
                'image' => 'images/testing.png',
                'description' => 'Identify and fix programming errors like a pro. Master debugging techniques, learn to use debugging tools, and develop systematic approaches to solve complex programming issues.',
            ],
            [
                'slug' => 'graphic-designing',
                'name' => 'Graphic Designing',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1700,
                'earlybird_fee' => 1400,
                'image' => 'images/graphic-design.png',
                'description' => 'Learn creative design for digital media. Master design principles, typography, color theory, and create stunning visual content for various digital platforms.',
            ],
            [
                'slug' => 'internet-of-things',
                'name' => 'Internet of Things',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1900,
                'earlybird_fee' => 1600,
                'image' => 'images/iot.png',
                'description' => 'Connect devices and build smart systems. Learn IoT architecture, sensor integration, data collection, and create connected solutions for smart environments.',
            ],
            [
                'slug' => 'netquest',
                'name' => 'NetQuest',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1200,
                'earlybird_fee' => 1000,
                'image' => 'images/cyber-security.png',
                'description' => 'Test your networking and cyber knowledge. Challenge yourself with network security scenarios, learn about protocols, and master cybersecurity fundamentals.',
            ],
            [
                'slug' => 'portable-robo-display',
                'name' => 'Portable Robo Display',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1500,
                'earlybird_fee' => 1200,
                'image' => 'images/robot.png',
                'description' => 'Build and showcase small robotic projects. Learn robotics fundamentals, programming, and create impressive robotic displays for competitions and exhibitions.',
            ],
            [
                'slug' => 'neural-network-design',
                'name' => 'Neural Network Design',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1800,
                'earlybird_fee' => 1500,
                'image' => 'images/neural-network.png',
                'description' => 'Design simple neural networks for AI projects. Learn the fundamentals of artificial neural networks, backpropagation, and create your first AI models.',
            ],
            [
                'slug' => 'machine-learning',
                'name' => 'Machine Learning',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 2500,
                'earlybird_fee' => 2000,
                'image' => 'images/brain.png',
                'description' => 'Learn how machines can learn from data. Master supervised and unsupervised learning algorithms, data preprocessing, and build predictive models.',
            ],
            [
                'slug' => 'startup-idea',
                'name' => 'Start-ups 101',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1500,
                'earlybird_fee' => 1200,
                'image' => 'images/start-up.png',
                'description' => 'Brainstorm and pitch innovative business ideas. Learn entrepreneurship fundamentals, business model canvas, and develop your startup pitch.',
            ],
            [
                'slug' => 'line-following-robot',
                'name' => 'Line Following Robot',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1800,
                'earlybird_fee' => 1500,
                'image' => 'images/delivery.png',
                'description' => 'Build a robot that follows a path automatically. Learn sensor integration, motor control, and create an autonomous line-following robot.',
            ],
            [
                'slug' => 'final-year-project-showcase',
                'name' => 'Final Year Project Showcase',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1500,
                'earlybird_fee' => 1200,
                'image' => 'images/project.png',
                'description' => 'Present your major project to peers and mentors. Showcase your final year project, get feedback from industry experts, and network with potential employers.',
            ],
            [
                'slug' => 'logic-designing',
                'name' => 'Logic Designing',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1200,
                'earlybird_fee' => 1000,
                'image' => 'images/logical-thinking.png',
                'description' => 'Practice logical thinking through circuits and designs. Learn digital logic, circuit design, and develop problem-solving skills through hands-on projects.',
            ],
            [
                'slug' => 'robowar',
                'name' => 'RoboWar',
                'type' => 'module',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1800,
                'earlybird_fee' => 1500,
                'image' => 'images/robotic-arm.png',
                'description' => 'Compete in building and battling robots. Design, build, and program combat robots to compete in exciting robotic battles.',
            ],
            [
                'slug' => 'python-bootcamp',
                'name' => 'Python Bootcamp',
                'type' => 'workshop',
                'team_min' => 1,
                'team_max' => 1,
                'fee' => 800,
                'earlybird_fee' => null,
                'image' => 'images/python.png',
                'description' => 'Hands-on Python coding workshop for beginners. Learn Python fundamentals, data structures, and build your first applications in this intensive workshop.',
                'duration' => '3 hours',
            ],
            [
                'slug' => 'robotics-hands-on',
                'name' => 'Robotics Hands-On',
                'type' => 'workshop',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1200,
                'earlybird_fee' => null,
                'image' => 'images/robotic-surgery.png',
                'description' => 'Build and program your first robot from scratch. Learn robotics fundamentals, programming, and create a working robot that you can take home.',
                'duration' => '4 hours',
            ],
            [
                'slug' => 'web-development',
                'name' => 'Web Development',
                'type' => 'workshop',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1000,
                'earlybird_fee' => null,
                'image' => 'images/coding.png',
                'description' => 'Learn to build websites from scratch.',
            ],
            [
                'slug' => 'mobile-app-development',
                'name' => 'Mobile App Development',
                'type' => 'workshop',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1300,
                'earlybird_fee' => null,
                'image' => 'images/app-development.png',
                'description' => 'Create mobile apps for iOS and Android.',
            ],
            [
                'slug' => 'data-science',
                'name' => 'Data Science',
                'type' => 'workshop',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1500,
                'earlybird_fee' => null,
                'image' => 'images/data-science.png',
                'description' => 'Analyze data and extract insights.',
            ],
            [
                'slug' => 'graphic-design-crash-course',
                'name' => 'Graphic Design Crash Course',
                'type' => 'workshop',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1200,
                'earlybird_fee' => null,
                'image' => 'images/pen-tool.png',
                'description' => 'Learn essential tools and techniques for digital design. Master Adobe Creative Suite, create stunning visuals, and develop your creative skills in this intensive workshop.',
                'duration' => '2 hours',
            ],
            [
                'slug' => 'animation-basics',
                'name' => 'Animation Basics',
                'type' => 'workshop',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 1400,
                'earlybird_fee' => null,
                'image' => 'images/animation.png',
                'description' => 'Create simple animations and motion graphics. Learn the fundamentals of animation, keyframe techniques, and bring your ideas to life with professional animation tools.',
                'duration' => '3 hours',
            ],
            [
                'slug' => 'ai-in-2026',
                'name' => 'AI in 2026',
                'type' => 'webinar',
                'team_min' => 1,
                'team_max' => 1,
                'fee' => 500,
                'earlybird_fee' => null,
                'image' => 'images/artificial-intelligence.png',
                'description' => 'Explore the future of artificial intelligence with an expert. Learn about cutting-edge AI technologies, machine learning trends, and what to expect in the coming years.',
                'speaker' => 'Mr. Ahmed',
                'date' => '2026-01-25',
            ],
            [
                'slug' => 'cybersecurity-trends',
                'name' => 'Cybersecurity Trends',
                'type' => 'webinar',
                'team_min' => 1,
                'team_max' => 1,
                'fee' => 400,
                'earlybird_fee' => null,
                'image' => 'images/cyber-security.png',
                'description' => 'Latest trends in cybersecurity.',
            ],
            [
                'slug' => 'cloud-computing',
                'name' => 'Cloud Computing',
                'type' => 'webinar',
                'team_min' => 1,
                'team_max' => 1,
                'fee' => 600,
                'earlybird_fee' => null,
                'image' => 'images/cloud.png',
                'description' => 'Introduction to cloud services.',
            ],
            [
                'slug' => 'blockchain-technology',
                'name' => 'Blockchain Technology',
                'type' => 'webinar',
                'team_min' => 1,
                'team_max' => 1,
                'fee' => 700,
                'earlybird_fee' => null,
                'image' => 'images/blockchain.png',
                'description' => 'Understanding blockchain and crypto.',
            ],
            [
                'slug' => 'iot-innovation',
                'name' => 'IoT Innovation',
                'type' => 'webinar',
                'team_min' => 1,
                'team_max' => 1,
                'fee' => 550,
                'earlybird_fee' => null,
                'image' => 'images/iot.png',
                'description' => 'Innovations in IoT.',
            ],
            [
                'slug' => 'startups-101',
                'name' => 'Startups 101',
                'type' => 'webinar',
                'team_min' => 1,
                'team_max' => 1,
                'fee' => 600,
                'earlybird_fee' => null,
                'image' => 'images/idea.png',
                'description' => 'Learn the fundamentals of launching and running a startup. Discover business strategies, funding options, and how to turn your innovative ideas into successful ventures.',
                'speaker' => 'Ms. Sana',
                'date' => '2026-01-28',
            ],
            [
                'slug' => 'code-sprint-2026',
                'name' => 'Code Sprint 2026',
                'type' => 'competition',
                'team_min' => 1,
                'team_max' => 3,
                'fee' => 1000,
                'earlybird_fee' => null,
                'image' => 'images/agile.png',
                'description' => 'Solve coding challenges in a timed competitive environment. Test your programming skills against other participants in this exciting coding competition.',
                'prize' => 15000,
            ],
            [
                'slug' => 'hackathon',
                'name' => 'Hackathon',
                'type' => 'competition',
                'team_min' => 2,
                'team_max' => 4,
                'fee' => 1500,
                'earlybird_fee' => null,
                'image' => 'images/hackathon.png',
                'description' => 'Collaborate to create innovative tech solutions in a set time. Work in teams to build amazing projects and compete for exciting prizes.',
                'prize' => 25000,
            ],
            [
                'slug' => 'robowar-challenge',
                'name' => 'RoboWar Challenge',
                'type' => 'competition',
                'team_min' => 2,
                'team_max' => 4,
                'fee' => 1200,
                'earlybird_fee' => null,
                'image' => 'images/military-robot.png',
                'description' => 'Compete with your robot against others in battles. Design, build, and program your robot to compete in exciting robotic combat challenges.',
                'prize' => 30000,
            ],
            [
                'slug' => 'app-development-contest',
                'name' => 'App Development Contest',
                'type' => 'competition',
                'team_min' => 1,
                'team_max' => 3,
                'fee' => 800,
                'earlybird_fee' => null,
                'image' => 'images/app-development.png',
                'description' => 'Build the best mobile app.',
            ],
            [
                'slug' => 'data-analysis-competition',
                'name' => 'Data Analysis Competition',
                'type' => 'competition',
                'team_min' => 1,
                'team_max' => 2,
                'fee' => 900,
                'earlybird_fee' => null,
                'image' => 'images/data-science.png',
                'description' => 'Analyze datasets and present findings.',
            ],
        ];

        foreach ($modules as $module) {
            DB::table('modules')->updateOrInsert(
                ['slug' => $module['slug']],
                $module
            );
        }
    }
}
